
[functions.send-rsvp-confirmation]
enabled = true
verify_jwt = true
import_map = "./functions/send-rsvp-confirmation/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-rsvp-confirmation/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-rsvp-confirmation/*.html" ]

[functions.geocode-parish]
enabled = true
verify_jwt = true
import_map = "./functions/geocode-parish/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/geocode-parish/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/geocode-parish/*.html" ]
